### PR TITLE
Eq in normalization

### PR DESCRIPTION
**Pull request by domluna**
Transforms `=` to `in` if part of a for loop condition, ref https://github.com/domluna/JuliaFormatter.jl/issues/34. Kind of funny, calling format on the package after this changed a loop condition. I guess it works 😄 

@StefanKarpinski any other test cases you think would be good?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Isn't this the opposite rule from what I proposed?

**Comment by domluna** [comment]
Hmmm, I guess misinterpreted it and now I'm kind of confused.

> However, this superficial syntax difference can help catch a common error, which is writing `for i = n` when you meant to write `for i = 1:n`. If we require `in` there then the programmer will notice that `for i in n` is not what they meant to write and catch the bug.

Doesn't argue for replacing `=` with `in`?

Follow up - would we use `=` only if it's a range like `1:10`?

**Comment by domluna** [comment]
Using the correct/incorrect examples #34 

Correct (these remain the same)

```julia
for i = 1:n
    println(i)
end

for i in itr
    println(i)
end
```
Incorrect

```julia
# remains the same
for i in 1:n
    println(i)
end

# `=` is replaced with `in`
for i = itr
    println(i)
end
```

So only the last example would warrant an actual transformation. Is this in line with what you meant?

**Comment by StefanKarpinski** [comment]
> Follow up - would we allow `=` only if it's a range like `1:10`?

Yes, and only allow `=` if the RHS is a range. So both of the later "incorrect" examples would be transformed:
* `for i in 1:n` would be turned into `for i = 1:10` and
* `for i = itr` would be turned into `for i in itr`.

**Comment by domluna** [comment]
@StefanKarpinski I think this does what it should now.

**Pull request merged**
