### PR TITLE
Fix ugly line breaks in curly braces outside of page margin when using `SciMLStyle` with `yas_style_nesting=true`

### PR DESCRIPTION
**Pull request by efaulhaber**
On master, this
```julia
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx::SomePrettyLongTypeName{Foo}
```
will be reformatted to this:
```julia
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx::SomePrettyLongTypeName{
                                                                                            Foo
                                                                                            }
```

I modified `p_curly` of `YASStyle` to not always insert a `Placeholder(0)` but add a `Placeholder(1)` when `whitespace_typedefs=true`. This is identical to what is done in `DefaultStyle`. With this change, I can use `p_curly` of `YASStyle` for `SciMLStyle` as well when `yas_style_nesting=true`.

Here is a demonstration of what happens in a large project when reformatted with this PR:
https://github.com/trixi-framework/Trixi.jl/pull/1759

IMHO, many things get prettier, and everything else gets, well, at least not uglier `¯\_(ツ)_/¯`
The only thing that gets slightly worse IMO is the file `src/solvers/dgmulti/sbp.jl`, but that wasn't pretty to begin with.

### CODE REVIEW

**Comment by domluna** [comment]
this looks good to me. seems ready to merge anything else you want to add?

**Comment by efaulhaber** [comment]
Ready to merge from my side.

**Comment by efaulhaber** [comment]
Thanks! When do you expect the next release?

**Comment by hyrodium** [comment]
v1.0.43 is going to be registered, but is failing automerge.
https://github.com/JuliaRegistries/General/pull/96136

**Pull request merged**
