### PR TITLE
Fix `join_lines_based_on_source` description

### PR DESCRIPTION
**Pull request by mroavi**
Swaps the descriptions for the `true` and `false` values for this option.

### CODE REVIEW

**Comment by domluna** [comment]
The current description looks correct to me.

What's the confusion here?

**Comment by mroavi** [comment]
It currently says:

> When `false` and the maximum margin is > than the length of "function foo(arg1, arg2, arg3)" this is formatted to
> ```julia
> function foo(arg1, arg2, arg3)
>    body
> end
> ```

According to me, It should be the opposite: when `true` the lines are joined, resulting in the formatted code above. I'm I wrong?

**Comment by mroavi** [comment]
I'm using the default configuration, which means that this option is set to `false` (as stated in the docs).
If I format:
```julia
function foo(arg1,
                       arg2, arg3
                       )
       body
end
```
I obtain:
```julia
function foo(arg1,
  arg2, arg3
)
  body
end
```
which is not joining the lines, unlike in the example posted in the previous comment.

**Comment by domluna** [comment]
what style are you using ? the option may be set as part of that style

**Comment by mroavi** [comment]
Hmm, perhaps I misunderstood what is meant by `source`. What exactly does it mean in this context?

**Comment by mroavi** [comment]
This PR doesn't make sense indeed. I'm closing it. But I still think that the intended meaning of the word "join" in this description is unclear. If you agree, I can open an issue.

**Pull request closed without merging**
