### PR TITLE
BlueStyle - implement top 3 issues

### PR DESCRIPTION
**Pull request by domluna**
Starts work on `BlueStyle` by implementing top 3 issues

ref https://github.com/domluna/JuliaFormatter.jl/issues/283#issuecomment-695243244

### CODE REVIEW

**Comment by domluna** [comment]
@nickrobinson251 which public repo would be good to run this on?

**Comment by nickrobinson251** [comment]
> which public repo would be good to run this on?

Most things in `invenia/` attempt to follow BlueStyle, afaik. 

some that might be interesting to run on (to see what changes are made):
- invenia/NamedDims
- invenia/LibPQ
- juliadiff/ChainRulesCore

**Comment by nickrobinson251** [comment]
Had a go at running on the NamedDims code-base 😺 
https://github.com/invenia/NamedDims.jl/pull/137

I'll be interested to see this on a few more codebases, but so far this looks brilliant.

**Comment by domluna** [comment]
Cool if I merge this as is then?

**Comment by nickrobinson251** [comment]
Yeah, sounds good to me! I guess we want to wait on releasing a version that exports BlueStyle til a bit more is implemented? Thh it's pretty close at this point

**Comment by nickrobinson251** [comment]
Thanks so much!

**Comment by domluna** [comment]
I can add a note/doc saying it's a WIP/experimental

**Comment by nickrobinson251** [comment]
Actually, there's a bug in the keyword detection -- it get's it wrong for definitions, see e.g. https://github.com/invenia/NamedDims.jl/pull/138/files#diff-60ebf9ed5f28a6130a00a9ea41458a4aR65

**Comment by domluna** [comment]
ok fixed that bug

**Comment by nickrobinson251** [comment]
Thanks! LGTM 🚀

**Comment by nickrobinson251** [comment]
Just noticed this https://github.com/invenia/LibPQ.jl/pull/197#discussion_r492739581

`BlueStyle()` should set `annotate_untyped_fields_with_any=false`

**Comment by domluna** [comment]
@nickrobinson251 im gonna remove the trailing comma from the cases where args fit on one line and then merge this in

**Comment by nickrobinson251** [comment]
> remove the trailing comma in that case right?

Yeah, that was decided. 

Thank you so much! 💙

**Pull request merged**
