### PR TITLE
Hotfix for #785

### PR DESCRIPTION
**Pull request by efaulhaber**
I don't know why this wasn't failing the tests in #785, but I think this is what's failing https://github.com/JuliaRegistries/General/pull/96136.

### CODE REVIEW

**Comment by domluna** [comment]
there is no format check in the CI so I don't know why that would cause registration to fail. either way we'll see if this works

**Comment by efaulhaber** [comment]
```
Failed to precompile JuliaFormatter [98e50ef6-434e-11e9-1051-2b60c6c9e899] to "/tmp/jl_dBrbRZ/compiled/v1.9/JuliaFormatter/jl_q3BnuY".
[ Info: Error in formatting file /tmp/jl_dBrbRZ/packages/JuliaFormatter/O48b1/test/sciml_style.jl
ERROR: LoadError: TaskFailedException

    nested task error: TaskFailedException
    
        nested task error: SystemError: opening file "/tmp/jl_dBrbRZ/packages/JuliaFormatter/O48b1/test/sciml_style.jl": Permission denied
```
I have absolutely no idea why it can't read this file, so my only guess is that it might be related to
```
[ Info: Error in formatting file /tmp/jl_dBrbRZ/packages/JuliaFormatter/O48b1/test/sciml_style.jl
```

**Comment by domluna** [comment]
maybe it's that the file gets modified during the test due to the format call. but the format test should have failed then so that's a bit weird

**Comment by domluna** [comment]
running locally it said

julia> format(".")
true

which is incorrect since there was a diff

λ ~/.julia/dev/JuliaFormatter: git diff
diff --git a/test/sciml_style.jl b/test/sciml_style.jl
index 3fe09c60..3d89595b 100644
--- a/test/sciml_style.jl
+++ b/test/sciml_style.jl
@@ -372,5 +372,5 @@
     # xxxxx::SomePrettyLongTypeName{
     #                               Foo
     #                              }
-    @test format_text(str, SciMLStyle(), yas_style_nesting=true) == str
+    @test format_text(str, SciMLStyle(), yas_style_nesting = true) == str
 end

**Comment by efaulhaber** [comment]
That explains why I didn't catch it. But shouldn't `format(".")` return `true` if and only if there is no diff? I rely on this return value in the CI checks in my code.

**Comment by domluna** [comment]
yeah this is the only time I've seen it fail

**Comment by domluna** [comment]
with -t auto (threads) it seems to work as well

**Pull request merged**
