### PR TITLE
V2 Fixes

### LINKED ISSUE #878: New formatting turns optional positional argument into keyword argument
Kudos on the full rewrite!
Unfortunately I have encountered a bug when I tried to apply the new formatting in https://github.com/gdalle/DifferentiationInterface.jl/pull/589. An unnamed, `Val`-typed positional argument was "formatted" into a keyword argument (see [this comment](https://github.com/gdalle/DifferentiationInterface.jl/pull/589/files#r1803531574)).

Schematically, the following code
```julia
function f(x, y, ::Val{N}=Val(1)) where {N}
```
turned into (note the semicolon)
```julia
function f(x, y; (::Val{N})=Val(1)) where {N}
```
which changed the semantics.

EDIT: As discussed below, this apparently applied to all _optional_ positional arguments, named or not. It might be due to BlueStyle.

### PR DESCRIPTION
**Pull request by domluna**
fixes #878 

```
     open(path, "w") do io
-        TOML.print(io, data)
+        return TOML.print(io, data)
     end
```

The `return` is no longer added for `do` expressions.

### CODE REVIEW

**Comment by ararslan** [comment]
> The `return` is no longer added for `do` expressions.

Is it not possible to support that? It's a requirement for YASGuide.

**Comment by domluna** [comment]
> > The `return` is no longer added for `do` expressions.
> 
> Is it not possible to support that? It's a requirement for YASGuide.

Is the example above, with the return added, not a dealbreaker for YAS? It's really tricky to only add return in cases where not nothing is returned. I think in v1 this was broken in a bunch of ways but functional enough that it worked for the most cases. In v2 this was fixed but the downside is that you get `return TOML.print(io, data)`.

**Comment by ararslan** [comment]
> It's really tricky to only add return in cases where not nothing is returned.

I'm not sure about the other style guides but at least for YAS the `return` is always required, even if it's `nothing`. In that example, `return TOML.print(io, data)` is correct for YAS. I'd probably personally write it as separate `TOML.print(io, data)` + `return nothing` but that's functionally equivalent and I wouldn't expect a formatter to be able to know that `TOML.print` is used for its side effects (writing to `io`) and not for its return value. Sounds like it's fully correct for YAS in v2 then?

**Comment by domluna** [comment]
> > It's really tricky to only add return in cases where not nothing is returned.
> 
> I'm not sure about the other style guides but at least for YAS the `return` is always required, even if it's `nothing`. In that example, `return TOML.print(io, data)` is correct for YAS. I'd probably personally write it as separate `TOML.print(io, data)` + `return nothing` but that's functionally equivalent and I wouldn't expect a formatter to be able to know that `TOML.print` is used for its side effects (writing to `io`) and not for its return value. Sounds like it's fully correct for YAS in v2 then?

I'll put this back in for YAS style.

> I wouldn't expect a formatter to be able to know that `TOML.print` is used for its side effects (writing to `io`) and not for its return value.

right, we would need to do side effect analysis which is out of scope for a formatter from my PoV.

**Comment by domluna** [comment]
Merging this to master, still some things we can do but this had most of the fixes in.

**Comment by RoyCCWang** [comment]
Thanks for everyone's work on this. May we please get a new release to get all these merged changes to the end user? I think just the #886  change along can encourage more Julia developers to consider writing non-exported public APIs, and It'll address #890 and #892 too.

**Pull request merged**
