### PR TITLE
do not write formatted string to file at all if overwrite==false

### LINKED ISSUE #363: Add feature to check if code is formatted correctly
Users may want to check if code is formatted correctly as part of a CI pipeline.  The ```check_format()``` function should only return true/false whether the code is correctly formatted, but *not* change anything if incorrectly formatted.  It should be the user's responsibility to fix the code formatting how he/she sees fit.

### PR DESCRIPTION
**Pull request by baumgold**
Closes #363

### CODE REVIEW

**Comment by domluna** [comment]
bin/format.jl hasn't been updated in a while, IMO it should be deleted.

Doesn't https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml#L34-L42 do the same thing?

**Comment by baumgold** [comment]
> bin/format.jl hasn't been updated in a while, IMO it should be deleted.

Sounds good to me.

> Doesn't https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml#L34-L42 do the same thing?

Yes but it only works for CI systems that use Github Actions.  I think a generic tool that can be called from any CI system would be useful.

**Comment by domluna** [comment]
ic - well that snippet could be copied over, GHA is not a requirement for it.

**Comment by baumgold** [comment]
> ic - well that snippet could be copied over, GHA is not a requirement for it.

That snippet depends on calling ```format(".", verbose=true)``` on L32 which modifies the files in-place.  My goal here is to be able to call ```format(".", overwrite=false)``` to check whether the files are formatted correctly without modifying the files.

**Comment by domluna** [comment]
Ok that makes sense - the current overwrite functionality is not useful anyway so this looks good.

Can you update the docs here https://github.com/domluna/JuliaFormatter.jl/blob/acf788c3c9ebfc6532912534486325ca74748cf4/src/JuliaFormatter.jl#L386-L388

**Pull request merged**
