### PR TITLE
change default for YAS to set `join_lines_based_on_source=true` by default

### LINKED ISSUE #423: do not remove style-compliant linebreaks
I'd like to expand the line length limit in my project via setting `margin` fairly high. However, reformatting after doing this will cause JuliaFormatter to try to fit everything on one line:

```diff
@@ -63,8 +63,7 @@ end
 function upsert(target::HasuraHTTPTarget, table_name, row; returning=["__typename"])
     mutation_target_name = string("upsert_", table_name)
     mutation_argument_name = :objects
-    mutation = (query=hasura_insert_mutation_string(mutation_target_name, mutation_argument_name, returning),
-                variables=to_hasura_gql((; mutation_argument_name => [row])))
+    mutation = (query=hasura_insert_mutation_string(mutation_target_name, mutation_argument_name, returning), variables=to_hasura_gql((; mutation_argument_name => [row])))
     response = HTTP.post(target.url, target.headers, JSON3.write(mutation))
     response_json = JSON3.read(String(response.body))
     if haskey(response_json, :data)
```

Both the "before" and "after" representations are YAS-compliant, but I as the author prefer the former representation. My naive opinion is that if code is already compliant with the chosen style guide, it should generally be considered to be in the purview of "author's choice" and left alone.

Is there a way for me to disable this behavior?

### PR DESCRIPTION
**Pull request by kleinschmidt**
WIP, not sure about tests but want to see what CI thinks

fixes #423 for YAS users at least, of which we can certainly count @jrevels who opened the issue :)

### CODE REVIEW

**Comment by domluna** [comment]
CI will probably fail

**Comment by domluna** [comment]
Only a handful fail, for those I think it's fine to manually set  `join_lines_based_on_source` to false.

**Comment by domluna** [comment]
I think you need to resolve the conflict for the tests to run

**Comment by kleinschmidt** [comment]
looks like it needs an approval @domluna

**Comment by domluna** [comment]
can you run format on the repo, probably some files in the YAS subdir are a little different

**Comment by kleinschmidt** [comment]
I think it was that i used `, key=val` in all my tests kwargs :joy:

**Review by domluna — APPROVED** [review]
haha nice

**Comment by domluna** [comment]
this LGTM any last things or we g2g?

**Comment by kleinschmidt** [comment]
Looks good as far as I'm concerned!

**Pull request merged**
