### PR TITLE
Begin to attempt to add trailing zeros to Float literals

### PR DESCRIPTION
**Pull request by odow**
So I wanted to implement adding trailing zeros to Float literals (https://github.com/domluna/JuliaFormatter.jl/issues/61), but I quickly got stuck. 

I haven't quite got my head around `PTree`s, so I'm stumbling around in the dark.

Is this the correct way to implement this? Or do I need to add a node to the tree like you did here:
https://github.com/domluna/JuliaFormatter.jl/commit/8944eaad622b8b88fa8b0f1d9e0dd7ef506fc742#diff-9915f66306b42c958fcd076dc0eee523R1228

At the moment I get
```Julia
julia> JuliaFormatter.format_text("1.")
"1.0"

julia> JuliaFormatter.format_text("1. + 1")
ERROR: Indexing range 1 - 6, index used = 7
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] cursor_loc at /Users/oscar/.julia/dev/JuliaFormatter/src/JuliaFormatter.jl:100 [inlined]
 [3] cursor_loc at /Users/oscar/.julia/dev/JuliaFormatter/src/JuliaFormatter.jl:102 [inlined]
 [4] p_literal(::CSTParser.EXPR, ::JuliaFormatter.State) at /Users/oscar/.julia/dev/JuliaFormatter/src/pretty.jl:386
 [5] pretty(::CSTParser.EXPR, ::JuliaFormatter.State) at /Users/oscar/.julia/dev/JuliaFormatter/src/pretty.jl:192
 [6] #p_binarycall#11(::Bool, ::Bool, ::Function, ::CSTParser.EXPR, ::JuliaFormatter.State) at /Users/oscar/.julia/dev/JuliaFormatter/src/pretty.jl:1139
 [7] p_binarycall(::CSTParser.EXPR, ::JuliaFormatter.State) at /Users/oscar/.julia/dev/JuliaFormatter/src/pretty.jl:1091
 [8] pretty(::CSTParser.EXPR, ::JuliaFormatter.State) at /Users/oscar/.julia/dev/JuliaFormatter/src/pretty.jl:252
 [9] pretty(::CSTParser.EXPR, ::JuliaFormatter.State) at /Users/oscar/.julia/dev/JuliaFormatter/src/pretty.jl:307
 [10] #format_text#52(::Int64, ::Int64, ::Function, ::String) at /Users/oscar/.julia/dev/JuliaFormatter/src/JuliaFormatter.jl:135
 [11] format_text(::String) at /Users/oscar/.julia/dev/JuliaFormatter/src/JuliaFormatter.jl:123
 [12] top-level scope at none:0
```

### CODE REVIEW

**Comment by domluna** [comment]
@odow This looks like it's on the right track. https://github.com/julia-vscode/CSTParser.jl/blob/master/src/spec.jl is the best reference for node types. The only new types introduced in the formatter are `PLeaf` types.

You shouldn't be editing the CST from `CSTParser`, it's just used to create the `PTree`. We probably also want to add an additional check besides just val[end] == '.'. I'm not sure if this occurs in other cases besides floats without a trailing zero.

This should work:

```julia
        val = x.val
        if x.kind === Tokens.FLOAT && val[end] == '.'
            val *= '0'
        end
        return PTree(x, loc[1], loc[1], val)
```

Token types are found in https://github.com/JuliaLang/Tokenize.jl/blob/master/src/token_kinds.jl

**Comment by domluna** [comment]
BTW Does the trailing zero come up at all with complex numbers or would this already that?

**Comment by domluna** [comment]
LGTM. Let me know if it's ready to merge in or if you're still making changes.

**Comment by odow** [comment]
Thanks for you help. I was missing the fact that the `x.val` argument to the `PTree` didn't have to be `x.val`.

I believe `Tokens.FLOAT` is the only case where there can be a trailing `.`. I've added tests with complex number examples. 

What's the policy on running `format("src")` and `format("test")` on a PR? Because there seemed to be a lot of indentation changes, but I didn't include them because they seemed unrelated.

**Comment by domluna** [comment]
No problem. I need to add more documentation to this thing so it's kind of my fault :upside_down_face: . 

Generally I do `format("src")` and `format("test/runtests.jl")`.

**Comment by odow** [comment]
I guess one hack would be to add 
```Julia
format(joinpath(dirname(@__DIR__, "src")))
format(@__FILE__)
```
to the bottom of `test/runtests.jl` so that anyone running the tests also auto-formats things.

**Comment by domluna** [comment]
that or GH support can get back to me so I can get this to work https://github.com/domluna/JuliaFormatter-action :smile: 

Anyway I'm gonna merge this in, thanks again!

**Pull request merged**
