### PR TITLE
bump CSTParser version

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by domluna** [comment]
Thanks @aviatesk.

**Comment by aviatesk** [comment]
@domluna thanks for the quick response :)
Can you make a release including this PR ?

**Comment by domluna** [comment]
I guess, does this actually change anything though? I’d like to fix a bug
before tagging a new release

**Comment by aviatesk** [comment]
ah I mean, since Juno relies on your package (and also on CSTParser.jl), we need this in order to update our CSTParser.jl version.
ref: https://github.com/JunoLab/Atom.jl/pull/212

**Comment by domluna** [comment]
@aviatesk makes sense tagged a new release

**Pull request merged**
