### PR TITLE
format docstrings

### PR DESCRIPTION
**Pull request by bramtayl**
Ok, this should be mostly working now. Style and state should propagate to embedded code chunks. The only remaining issue is a problem with `\\` (see the one new test broken) that I was hoping someone else would understand.

### CODE REVIEW

**Comment by bramtayl** [comment]
Supercedes #225

**Comment by domluna** [comment]
So the failed case has to do with string escaping and unescaping, which is one of the reasons the string is read directly from the file and not via `.val` field of the CSTParser node. I think the markdown portion is doing something similar.

It would be best to check with some other example docstrings where escaping/unescaping would alter the output.

**Comment by bramtayl** [comment]
I wonder if this is a bug in `Markdown.plain`? To be honest once it gets to 4 backslashes I get kinda lost

```
"""
`\\` \\\\
"""
test(x) = x
Markdown.plain(@doc test) # doesn't match text above
```

**Comment by bramtayl** [comment]
Also, I'm very confused about the format check failure...not sure how to fix the formatting when I'm changing the formatting simultaneously...

**Comment by domluna** [comment]
You have to run format() on the JuliaFormatter.jl directly.

The check is mostly there as a sanity check reminder to make sure the change hasn't caused unwanted changes in the files. Sort of like an integration test.

**Comment by bramtayl** [comment]
Ok got it. Well that seems to error, which is strange because the tests pass...I'll do some digging

**Comment by bramtayl** [comment]
Bad news: I definitely introduced a bug that wasn't caught by the tests. Good news: I found an extra test that reveals the bug.

**Comment by bramtayl** [comment]
@domluna I can't figure out what's causing the bug, do you have any ideas?

**Comment by domluna** [comment]
I'll take a look tomorrow. Probably related to docstrings being eaten somehow though

**Comment by bramtayl** [comment]
@domluna sorry to bother you again. Just looking forward to very pretty docstrings. Did you get a chance to look at this?

**Comment by domluna** [comment]
feel free to bug me as much you like 🙂 . Could you rebase off master and push again?

Btw, regarding the rendering engine thing https://github.com/MichaelHatherly/CommonMark.jl looks promising but I haven't done a deep dive with it yet.

**Comment by mortenpi** [comment]
Just a drive-by comment, which may or may not be useful: In Documenter we need to do something similar when we want to update the doctest outputs automatically. The approach we have taken is to just [regex for the code blocks and then replace the content between the backticks](https://github.com/JuliaDocs/Documenter.jl/blob/fc08dfa1ab3cb09ce81df01037a74bfb7288c824/src/DocTests.jl#L391-L437). So we don't ever parse the Markdown, getting around the issue of the re-created Markdown not being identical to the original. And it seems to work quite reliably.

**Comment by bramtayl** [comment]
I think there's pluses and minuses of leaving the markdown part alone. On one hand, it guarantees round-trip-ability and is a lot simpler; on the other hand, there is potential to make markdown prettier too. Happy with either

**Comment by domluna** [comment]
example of hooking into CommonMark to format julia code blocks https://github.com/MichaelHatherly/CommonMark.jl/issues/4#issuecomment-638277469

**Comment by bramtayl** [comment]
Ooh that's nice!

**Comment by bramtayl** [comment]
Rebased as #247

**Pull request closed without merging**
